/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ddibyana' at '4/13/17 12:22 PM' with Gradle 2.13
 *
 * @author ddibyana, @date 4/13/17 12:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
